#!/usr/local/bin/bash

#author: Toni Mertanen
#Created: 1.8.2024
#Last modified: 1.8.2024

#Describtion: This script removes all the files in the given directory that are older than given days.

#Usage: ./cruft_remover.sh

#Prompt the user for the directory and the number of days
read -p "Enter the directory to check: " directory
read -p "Enter the number of days from last modification: " days

#Check the given directory for files that are older than the given days
readarray -d '' files < <(find "$directory" -mtime +"$days" -print0)

# Check if any files were found
if [ ${#files[@]} -eq 0 ]; then
    echo "No files found that are older than $days days in directory $directory."
    exit 0
fi

#Remove the files that are older than the given days with prompt
for file in "${files[@]}"; do
    rm -i "$file"
done

exit 0