#!bash

#Author: Toni Mertanen
#Created: 1.8.2024
#Last modified: 1.8.2024

#Description: This script organises the files in the given directory by moving them to the corresponding folders based on their file extensions.

#Usage: ./folder_organiser.sh

#Function to move a file to a directory
move_file_to_directory() {
    local file=$1
    local directory=$2

    # Check if the directory exists in the current directory
    if [ ! -d "$directory" ]; then
        echo "Directory '$directory' does not exist. Creating it now."
        mkdir "$directory"
        if [ $? -ne 0 ]; then
            echo "Failed to create directory '$directory'."
            return 1
        fi
    fi

    # Move the file to the directory
    mv "$file" "$directory"
    if [ $? -eq 0 ]; then
        echo "File '$file' has been moved to '$directory'."
    else
        echo "Failed to move the file '$file' to '$directory'."
        return 1
    fi
}


#Prompt the user if folder organisation is needed
read -p "Do you want to organise the files in the current directory? (y/n): " response
case "$response" in
  [yY][eE][sS]|[yY])
    echo "Organising files in the current directory..."
    ;;
  [nN][oO]|[nN])
    echo "Exiting the script..."
    exit 1
    ;;
  *)
    echo "Invalid input. Exiting the script..."
    exit 1
    ;;
esac

# List files in the current directory and process each file
ls | while read -r file; do
  echo "Processing file: $file"
  case "$file" in
    *.jpg|*.jpeg|*.png|*.gif|*.bmp|*.webp|*.svg)
      echo "Moving image file: $file"
      move_file_to_directory "$file" "images"
      ;;
    *.doc|*.docx|*.pdf|*.txt|*.odt|*.rtf)
      echo "Moving document file: $file"
      move_file_to_directory "$file" "documents"
      ;;
    *.mp4|*.mkv|*.avi|*.mov|*.flv|*.wmv)
      echo "Moving video file: $file"
      move_file_to_directory "$file" "videos"
      ;;
    *.mp3|*.wav|*.flac|*.ogg|*.wma)
      echo "Moving audio file: $file"
      move_file_to_directory "$file" "audio"
      ;;
    *.sh|*.bash|*.py|*.js|*.java|*.cpp|*.c|*.h|*.hpp)
      echo "Moving script file: $file"
      move_file_to_directory "$file" "scripts"
      ;;
    *.xls|*.xlsx|*.ods|*.csv)
      echo "Moving spreadsheet file: $file"
      move_file_to_directory "$file" "spreadsheets";;
    *.zip|*.tar|*.gz|*.bz2|*.7z|*.rar|*.bz2)
      echo "Moving archive file: $file"
      move_file_to_directory "$file" "archives";;
    *.ppt|*.pptx|*.odp)
      echo "Moving presentation file: $file"
      move_file_to_directory "$file" "presentations";;
    *)
      echo "File type not defined for organisizing: $file"
      ;;
  esac
done

exit 0