#!/bin/bash

# Author: Toni Mertanen
# Created: 3.12.2024
# Last modified: 3.12.2024

# Description: Echos current NODE_ENV

# Usage: ./nodeEnv

if [ -z "$NODE_ENV" ]; then
  echo "NODE_ENV is not set"
else
  echo "NODE_ENV is set to $NODE_ENV"
fi

exit 0