#!/bin/bash

#Author: Toni Mertanen
#Created: 1.8.2024
#Last modified: 1.8.2024

#Description: This script is a toolkit menu.

#Usage: ./toolkit.sh    

# Display menu
echo "Toolkit Menu"
echo "------------"
PS3="Please choose an option:"
#echo "1. Unused file removal"
#echo "2. Folder organisizer"

# Read user input
select option in "Unused file removal" "Folder organisizer" "Quit"; do
  case "$REPLY" in
    1)
      echo "You chose Unused file removal"
      ./cruft_remover
      break
      ;;
    2)
      echo "You chose Folder organisizer"
      ./folder_organiser
      break
      ;;
    3)
      echo "Exiting..."
      exit 0
      ;;
    *)
      echo "Invalid choice, please select 1 or 2 or 3."
      ;;
  esac
done

exit 0